### ISSUE TITLE
How to disable Router Guard for Development Environment

### ISSUE THREAD

**Issue by erhimanshugarg** [pnglabz/angular-routing-demo#1]
I have implemented Routing Guards in application to restrict unauthenticated access. I want the guards to be enabled only for Testing environment like UAT and Production Environment. Can anyone suggest how can i customize the Guards for environment specific work so that they won't  be enabled for Development environment.

**Comment by narendravaghela** [comment]
You can place environment check in your gaurd's `canActivate` method.

```javascript
import { environment } from '../environments/environment';

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> | Promise<boolean> | boolean {
    if (environment.production) {
      // do your job
    } else {
      return true;
    }
  }
```

**Comment by narendravaghela** [comment]
I hope the above example has resolved your issue. Closing it now...
